#pragma once
#include "cex.h"

f64 mylib_add(f64 a, f64 b);

struct __cex_namespace__mylib {
    // Autogenerated by CEX
    // clang-format off

    f64             (*add)(f64 a, f64 b);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__mylib mylib;

