#pragma once
#include <cex/cex.h>
#include <stdalign.h>
#include <stdint.h>
#include <stddef.h>

typedef struct
{
    alignas(64) const Allocator_i base;
    // below goes sanity check stuff
    u64 magic;
    struct
    {
        unsigned int n_allocs;
        unsigned int n_reallocs;
        unsigned int n_free;
        unsigned int n_fopen;
        unsigned int n_fclose;
        unsigned int n_open;
        unsigned int n_close;
    } stats;
} allocator_generic_s;
_Static_assert(sizeof(allocator_generic_s) == 128, "size!");
_Static_assert(offsetof(allocator_generic_s, base) == 0, "base must be the 1st struct member");

struct __class__AllocatorGeneric
{
    // Autogenerated by CEX
    // clang-format off

/**
 * @brief  heap-based allocator (simple proxy for malloc/free/realloc)
 */
IAllocator
(*create)(void);

IAllocator
(*destroy)(void);

    // clang-format on
};
extern const struct __class__AllocatorGeneric AllocatorGeneric; // CEX Autogen
