name: CEX Examples Build Action
inputs:
  shell:
    description: 'target shell'
    required: false
    default: 'bash'

runs:
  using: 'composite'

  steps:
    - name: Cex Example
      shell: ${{ inputs.shell }}
      run: |
        echo ""
        echo "---------------------------------------------------------------------"
        echo "           STEP: libs system + vcpkg system"
        echo "---------------------------------------------------------------------"
        cd examples/libs_sys/
        cc -g ./cex.c -o ./cex 
        ./cex config
        ./cex app run cex_downloader
        ./cex build-unzip
        ./cex app run cex_unzip
        ./cex help sqlite3.
        cd ./build
        ls -la

    - name: Cex Example
      shell: ${{ inputs.shell }}
      run: |
        echo ""
        echo "---------------------------------------------------------------------"
        echo "           STEP: libs vcpkg"
        echo "---------------------------------------------------------------------"
        cd examples/libs_vcpkg/
        cc -g ./cex.c -o ./cex 
        ./cex vcpkg-install
        ./cex config
        ./cex app run cex_downloader
        ./cex app run cex_unzip
        cd ./build
        ls -la

    - name: Cex Example
      shell: ${{ inputs.shell }}
      run: |
        echo ""
        echo "---------------------------------------------------------------------"
        echo "           STEP: example lua_module"
        echo "---------------------------------------------------------------------"
        cd examples/lua_module/
        cc -g ./cex.c -o ./cex 
        ./cex config
        ./cex build-lua
        ./cex build-lib
        ./cex test-lib

    - name: Cex Example
      shell: ${{ inputs.shell }}
      run: |
        echo ""
        echo "---------------------------------------------------------------------"
        echo "           STEP: example sqlite"
        echo "---------------------------------------------------------------------"
        cd examples/sqlite/
        cc -g ./cex.c -o ./cex 
        ./cex config
        ./cex
        ./build/hello_sqlite hello.db
        ./build/sqlite3 build/hello.db "SELECT * FROM Messages;"


