// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// NOTE: include in test as
//#include "tests/fake/include/cex/test/dst/AllocatorDST.h"


// clang-format off
#include <cex/test/fff.h>
#include <cex/cex.h>
#include "include/cex/test/dst/AllocatorDST.h"


FAKE_VALUE_FUNC(const Allocator_i*, AllocatorDST_create)
FAKE_VALUE_FUNC(const Allocator_i*, AllocatorDST_destroy)

const struct __class__AllocatorDST AllocatorDST = {
    // Autogenerated by CEX
    // clang-format off
    .create = AllocatorDST_create,
    .destroy = AllocatorDST_destroy,
    // clang-format on
};

// clang-format off


static void fake__AllocatorDST__resetall(void) {
    RESET_FAKE(AllocatorDST_create)
    RESET_FAKE(AllocatorDST_destroy)
}

