// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// NOTE: include in test as
//#include "tests/fake/include/cex/test/dst/DST.h"


// clang-format off
#include <cex/test/fff.h>
#include <cex/cex.h>
#include "include/cex/test/dst/DST.h"


FAKE_VALUE_FUNC(Exc, DST_create, u64)
FAKE_VALUE_FUNC(Exc, DST_setup, dst_params_s*)
FAKE_VALUE_FUNC(bool, DST__rnd__check, f32)
FAKE_VALUE_FUNC(bool, DST_tick, u32)
FAKE_VOID_FUNC(DST__fuzz__u64, u64*, u64 *, usize)
FAKE_VOID_FUNC(DST_sim_log_reset)
FAKE_VALUE_FUNC(Exc, DST_simulate, DSTSimulationFunc_f)
FAKE_VALUE_FUNC(f32, DST__rnd__prob)
FAKE_VALUE_FUNC(usize, DST__rnd__range, usize, usize)
FAKE_VOID_FUNC(DST_print_postmortem, void*)
FAKE_VOID_FUNC(DST_destroy)

const struct __class__DST DST = {
    // Autogenerated by CEX
    // clang-format off
    .create = DST_create,
    .setup = DST_setup,
    .tick = DST_tick,
    .sim_log_reset = DST_sim_log_reset,
    .simulate = DST_simulate,
    .print_postmortem = DST_print_postmortem,
    .destroy = DST_destroy,

    .rnd = {  // sub-module .rnd >>>
        .check = DST__rnd__check,
        .prob = DST__rnd__prob,
        .range = DST__rnd__range,
    },  // sub-module .rnd <<<

    .fuzz = {  // sub-module .fuzz >>>
        .u64 = DST__fuzz__u64,
    },  // sub-module .fuzz <<<
    // clang-format on
};

// clang-format off


static void fake__DST__resetall(void) {
    RESET_FAKE(DST_create)
    RESET_FAKE(DST_setup)
    RESET_FAKE(DST__rnd__check)
    RESET_FAKE(DST_tick)
    RESET_FAKE(DST__fuzz__u64)
    RESET_FAKE(DST_sim_log_reset)
    RESET_FAKE(DST_simulate)
    RESET_FAKE(DST__rnd__prob)
    RESET_FAKE(DST__rnd__range)
    RESET_FAKE(DST_print_postmortem)
    RESET_FAKE(DST_destroy)
}

