#!/usr/bin/env python3
import os
import io
import re


class Bundler:
    def __init__(self, cex_lib_dir: str, cex_bundle_dir: str):
        assert os.path.exists(cex_lib_dir)
        assert os.path.exists(cex_bundle_dir)

        assert os.path.exists(os.path.join(cex_lib_dir, "cex_base.h"))
        assert os.path.exists(os.path.join(cex_lib_dir, "cex_base.c"))

        assert os.path.exists(os.path.join(cex_lib_dir, "all.h"))

        self.cex_lib_path = cex_lib_dir
        self.cex_bundle_dir = cex_bundle_dir

    def parse_header(self, fn) -> list[str]:
        with open(fn) as fh:
            lines = fh.readlines()

        out = []
        for line in lines:
            if "#pragma once" in line:
                continue
            if re.search(r"#include\s+\"\w+\.[h|c]\"", line, re.MULTILINE):
                continue
            if re.search(r"#include\s+\<cex.*\.[h|c]\>", line, re.MULTILINE):
                continue
            out.append(line.rstrip())

        return out

    def parse_code(self, fn) -> list[str]:
        with open(fn) as fh:
            lines = fh.readlines()

        out = []
        for line in lines:
            if "#pragma once" in line:
                continue
            if re.search(r"#include\s+\"\w+\.[h|c]\"", line, re.MULTILINE):
                continue
            if re.search(r"#include\s+\<cex.*\.[h|c]\>", line, re.MULTILINE):
                continue
            out.append(line.rstrip())

        return out

    def bundle_headers(self):
        # NOTE: adding manually in order to preserve interdependencies
        headers = [
            "cex_base.h",
            "mem.h",
            "AllocatorHeap.h",
            "AllocatorArena.h",
            "ds.h",
            "_sprintf.h",
            "str.h",
            "sbuf.h",
            "io.h",
            "argparse.h",
            "_subprocess.h",
            "os.h",
            "test.h",
            "cexy.h",
            "CexLexer.h",
        ]
        print(f"Bundling: {headers}")
        hbuf = io.StringIO()
        hbuf.write("#ifndef CEX_HEADER_H\n")
        hbuf.write("#define CEX_HEADER_H\n")

        with open(os.path.join(self.cex_lib_path, "cex_header.h")) as fh:
            hbuf.write(fh.read())

        for h in headers:
            hbuf.write("\n\n")
            hbuf.write("/*\n")
            hbuf.write(f"*                   {h}\n")
            hbuf.write("*/\n")

            h_lines = self.parse_header(os.path.join(self.cex_lib_path, h))
            hbuf.write("\n".join(h_lines))

        hbuf.write("\n\n")
        hbuf.write("/*\n")
        hbuf.write("*                   CEX IMPLEMENTATION \n")
        hbuf.write("*/\n")
        hbuf.write("\n\n")
        hbuf.write("#ifdef CEX_IMPLEMENTATION\n")

        h_lines = self.parse_code(os.path.join(self.cex_lib_path, "cex_header.c"))
        hbuf.write("\n".join(h_lines))

        for h in headers:
            h = h.replace(".h", ".c")
            hbuf.write("\n\n")
            hbuf.write("/*\n")
            hbuf.write(f"*                   {h}\n")
            hbuf.write("*/\n")

            h_lines = self.parse_code(os.path.join(self.cex_lib_path, h))
            hbuf.write("\n".join(h_lines))

        hbuf.write("\n\n#endif // #ifdef CEX_IMPLEMENTATION\n")
        hbuf.write("\n\n#endif // #ifndef CEX_HEADER_H\n")

        # print(hbuf.getvalue())
        with open(os.path.join(self.cex_bundle_dir, "cex.h"), "w") as fh:
            fh.write(hbuf.getvalue())

    def bundle(self):
        self.bundle_headers()
        # self.bundle_code()
        pass


if __name__ == "__main__":

    b = Bundler("./include/cex/", "./")
    b.bundle()
