// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// NOTE: include in test as
//#include "tests/fake/include/cex/random/Random.h"


// clang-format off
#include <cex/test/fff.h>
#include <cex/cex.h>
#include "include/cex/random/Random.h"


FAKE_VALUE_FUNC(u32, Random_next, Random_c*)
FAKE_VOID_FUNC(Random_seed, Random_c*, u64)
FAKE_VALUE_FUNC(f32, Random_f32, Random_c*)
FAKE_VALUE_FUNC(i32, Random_i32, Random_c*, i32, i32)
FAKE_VALUE_FUNC(bool, Random_prob, Random_c*, f32)
FAKE_VALUE_FUNC(usize, Random_range, Random_c*, usize, usize)
FAKE_VOID_FUNC(Random_buf, Random_c*, void*, usize)

const struct __class__Random Random = {
    // Autogenerated by CEX
    // clang-format off
    .next = Random_next,
    .seed = Random_seed,
    .f32 = Random_f32,
    .i32 = Random_i32,
    .prob = Random_prob,
    .range = Random_range,
    .buf = Random_buf,
    // clang-format on
};

// clang-format off


static void fake__Random__resetall(void) {
    RESET_FAKE(Random_next)
    RESET_FAKE(Random_seed)
    RESET_FAKE(Random_f32)
    RESET_FAKE(Random_i32)
    RESET_FAKE(Random_prob)
    RESET_FAKE(Random_range)
    RESET_FAKE(Random_buf)
}

