#pragma once
#include "os.h"

#ifdef _WIN32
#include "_os_win.c"
#define ostr$sPATH_SEP '\\'
#else
#include "_os_posix.c"
#define ostr$sPATH_SEP '/'
#endif

Exception
os_listdir(const char* path, sbuf_c* out)
{
    return os__listdir_(path, out);
}

Exception
os_getcwd(sbuf_c* out)
{
    return os__getcwd_(out);
}

const char*
os_getenv(const char* name, const char* deflt)
{
    const char* result = getenv(name);

    if (result == NULL) {
        result = deflt;
    }

    return result;
}

void
os_setenv(const char* name, const char* value, bool overwrite)
{
    setenv(name, value, overwrite);
}

void
os_unsetenv(const char* name)
{
    unsetenv(name);
}

Exception
os__path__exists(const char* path)
{
    return os__path__exists_(path);
}

Exception
os__path__join(sbuf_c* out, const char* format, ...)
{

    va_list va;
    va_start(va, format);
    sbuf.clear(out);
    Exc result = sbuf.appendf(out, format, va);
    va_end(va);
    return result;
}

str_s
os__path__splitext(const char* path, bool return_ext)
{
    if(path == NULL) {
        return (str_s){0};
    }
    usize pathlen = strlen(path);
    if (pathlen == 0) {
        return str$s("");
    }

    usize last_char_idx = pathlen;
    usize last_dot_idx = pathlen;

    for (usize i = pathlen; i-- > 0;) {
        if (path[i] == '.') {
            if (last_dot_idx == pathlen) {
                last_dot_idx = i;
            }
        } else if (path[i] == '/' || path[i] == '\\') {
            break;
        } else if (last_dot_idx != pathlen) {
            last_char_idx = i;
            break;
        }
    }
    if (last_char_idx < last_dot_idx) {
        if (return_ext) {
            return str.sub(path, last_dot_idx, 0);
        } else {
            return str.sub(path, 0, last_dot_idx);
        }

    } else {
        if (return_ext) {
            return str$s("");
        } else {
            return str.sstr(path);
        }
    }
}


const struct __module__os os = {
    // Autogenerated by CEX
    // clang-format off
    .listdir = os_listdir,
    .getcwd = os_getcwd,
    .getenv = os_getenv,
    .setenv = os_setenv,
    .unsetenv = os_unsetenv,

    .path = {  // sub-module .path >>>
        .exists = os__path__exists,
        .join = os__path__join,
        .splitext = os__path__splitext,
    },  // sub-module .path <<<
    // clang-format on
};
