#pragma once
#include <cex/all.h>
#include <cex/os/subprocess.h>


typedef struct os_cmd_flags_s
{
    u32 combine_stdouterr : 1; // if 1 - combines output from stderr to stdout
    u32 no_inherit_env : 1;    // if 1 - disables using existing env variable of parent process
    u32 no_search_path : 1;    // if 1 - disables propagating PATH= env to command line
    u32 no_window : 1;         // if 1 - disables creation of new window if OS supported
} os_cmd_flags_s;
_Static_assert(sizeof(os_cmd_flags_s) == sizeof(u32), "size?");

typedef struct os_cmd_c
{
    struct subprocess_s _subpr;
    os_cmd_flags_s _flags;
    bool _is_subprocess;
} os_cmd_c;

struct __module__os
{
    // Autogenerated by CEX
    // clang-format off

void            (*sleep)(u32 period_millisec);

struct {  // sub-module .fs >>>
    Exception       (*getcwd)(sbuf_c* out);
    Exception       (*listdir)(const char* path, sbuf_c* out_buf);
    Exception       (*mkdir)(const char* path);
    Exception       (*remove)(const char* path);
} fs;  // sub-module .fs <<<

struct {  // sub-module .env >>>
    const char*     (*get)(const char* name, const char* deflt);
    void            (*set)(const char* name, const char* value, bool overwrite);
    void            (*unset)(const char* name);
} env;  // sub-module .env <<<

struct {  // sub-module .path >>>
    Exception       (*exists)(const char* file_path);
    char*           (*join)(arr$(char*) parts, IAllocator allc);
    str_s           (*splitext)(const char* path, bool return_ext);
} path;  // sub-module .path <<<

struct {  // sub-module .cmd >>>
    Exception       (*create)(os_cmd_c* self, arr$(char*) args, arr$(char*) env, os_cmd_flags_s* flags);
    bool            (*is_alive)(os_cmd_c* self);
    Exception       (*join)(os_cmd_c* self, u32 timeout_sec, i32* out_ret_code);
    Exception       (*kill)(os_cmd_c* self);
    char*           (*read_all)(os_cmd_c* self, IAllocator allc);
    char*           (*read_line)(os_cmd_c* self, IAllocator allc);
    Exception       (*run)(const char** args, usize args_len, os_cmd_c* out_cmd);
    FILE*           (*stderr)(os_cmd_c* self);
    FILE*           (*stdin)(os_cmd_c* self);
    FILE*           (*stdout)(os_cmd_c* self);
    Exception       (*write_line)(os_cmd_c* self, char* line);
} cmd;  // sub-module .cmd <<<
    // clang-format on
};
extern const struct __module__os os; // CEX Autogen
