/**
 * @file
 * @brief General purpose pseudo-random number generator for CEX.
 */
#pragma once
#include "cex.h"

typedef struct Random_c
{
    u64 state[2]; // Random generator internal state
    u64 n_ticks;  // number of any Random() generator calls after last Random.seed()
} Random_c;

struct __class__Random
{
    // Autogenerated by CEX
    // clang-format off

/**
 * @brief Next random u32 number
 *
 * @param self 
 * @return 
 */
u32
(*next)(Random_c* self);

/**
 * @brief Resets seed of random generator (must be called before first use)
 *
 * @param self 
 * @param seed 
 */
void
(*seed)(Random_c* self, u64 seed);

/**
 * @brief Random floating point number in [0;1.0] range
 *
 * @param self 
 * @return 
 */
f32
(*f32)(Random_c* self);

/**
 * @brief Random i32 number in [min; max] range
 *
 * @param self 
 * @param min  minimum for range
 * @param max maximum for range (included!)
 * @return 
 */
i32
(*i32)(Random_c* self, i32 min, i32 max);

/**
 * @brief Random probability simulation (rolling a dice)
 *
 * @param self 
 * @param prob_threshold target probability of dice roll, between [0.0f;1.0f]
 * @return true dire roll if succeeded
 */
bool
(*prob)(Random_c* self, f32 prob_threshold);

/**
 * @brief Returning random range in [min; max). Useful for arrays.
 *
 * @param self 
 * @param min minimum start range (included)
 * @param max maximum end range (excluded)
 * @return 
 */
usize
(*range)(Random_c* self, usize min, usize max);

/**
 * @brief Fill buffer with randomized data
 *
 * @param self 
 * @param buf any buffer of memory
 * @param buf_len buffer capacity
 */
void
(*buf)(Random_c* self, void* buf, usize buf_len);

    // clang-format on
};
extern const struct __class__Random Random; // CEX Autogen
