/**
 * @file
 * @brief Deterministic Simulation Tester
 */
#pragma once
#include <cex/cex.h>
#include <cex/random/Random.h>
#include <stdatomic.h>
#include <time.h>

typedef Exc (*DSTSimulationFunc_f)(void);

typedef struct
{
    struct
    {
        // allocator->malloc / calloc / aligned / realloc
        f32 malloc_fail_prob;

        // allocator->fopen / open
        f32 open_fail_prob;
        i32 open_fail_errnos[32];
        u32 open_fail_errnos_len;

        // allocator->fclose / close
        f32 close_fail_prob;
        i32 close_fail_errnos[32];
        u32 close_fail_errnos_len;

    } allocators;

    struct {
        // if false - resets stdout/stderr log file every tick
        bool keep_tick_log;
    } simulator;

} dst_params_s;

typedef struct
{
    dst_params_s prm;
    atomic_flag _lock;
    atomic_flag _lock_rng;
    Random_c _rng;
    u64 _initial_seed;
    time_t _initial_time;
    u64 _tick_max;
    u64 _tick_current;
    FILE* _sim_log;
} DST_c;

extern DST_c _DST;

struct __class__DST
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*create)(u64 seed);

/**
 * @brief DST behavior configuration 
 *
 * @param prm params
 * @return 
 */
Exception
(*setup)(dst_params_s* prm);

/**
 * @brief DST loop step 
 *
 * @param max_ticks maximum loop steps
 * @return 
 */
bool
(*tick)(u32 max_ticks);

void
(*sim_log_reset)();

Exception
(*simulate)(DSTSimulationFunc_f simfunc);

/**
 * @brief Compatible function with test$set_postmortem(DST.print_postmortem, NULL)
 *
 * @param ctx
 */
void
(*print_postmortem)(void* ctx);

void
(*destroy)();


struct {  // sub-module .rnd >>>
    /**
     * @brief Make random dice roll and check if it passed given probability threshold
     *
     * @param prob_threshold >= 0 && < 1.0
     * @return 
     */
    bool
    (*check)(f32 prob_threshold);

    f32
    (*prob)();

    usize
    (*range)(usize min, usize max);

} rnd;  // sub-module .rnd <<<

struct {  // sub-module .fuzz >>>
    /**
     * @brief Fuzz out_value with some wild number
     *
     * @param out_value 
     * @param variants overrides fuzz randomness, and used values from given array
     * @param variants_len 
     */
    void
    (*u64)(u64* out_value, u64 variants[], usize variants_len);

} fuzz;  // sub-module .fuzz <<<
    // clang-format on
};
extern const struct __class__DST DST; // CEX Autogen
