/**
 * @file
 * @brief Deterministic Simulation Tester
 */
#pragma once
#include "cex.h"
#include <lib/random/Random.h>
#include <stdatomic.h>
#include <time.h>

typedef Exc (*DSTSimulationFunc_f)(void);

typedef struct
{
    struct
    {
        // allocator->malloc / calloc / aligned / realloc
        f32 malloc_fail_prob;

        // allocator->fopen / open
        f32 open_fail_prob;
        i32 open_fail_errnos[32];
        u32 open_fail_errnos_len;

        // allocator->fclose / close
        f32 close_fail_prob;
        i32 close_fail_errnos[32];
        u32 close_fail_errnos_len;

    } allocators;

    struct {
        // if false - resets stdout/stderr log file every tick
        bool keep_tick_log;
    } simulator;

} dst_params_s;

typedef struct
{
    dst_params_s prm;
    atomic_flag _lock;
    atomic_flag _lock_rng;
    Random_c _rng;
    u64 _initial_seed;
    time_t _initial_time;
    u64 _tick_max;
    u64 _tick_current;
    FILE* _sim_log;
} DST_c;

extern DST_c _DST;

struct __cex_namespace__DST {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(u64 seed);
    void            (*destroy)();
    /// Compatible function with test$set_postmortem(DST.print_postmortem, NULL)
    void            (*print_postmortem)(void* ctx);
    /// DST behavior configuration
    Exception       (*setup)(dst_params_s* prm);
    void            (*sim_log_reset)();
    Exception       (*simulate)(DSTSimulationFunc_f simfunc);
    /// DST loop step
    bool            (*tick)(u32 max_ticks);

    struct {
        /// Fuzz out_value with some wild number
        void            (*u64)(u64* out_value, u64 variants[], usize variants_len);
    } fuzz;

    struct {
        /// Make random dice roll and check if it passed given probability threshold
        bool            (*check)(f32 prob_threshold);
        f32             (*prob)();
        usize           (*range)(usize min, usize max);
    } rnd;

    // clang-format on
};
__attribute__((visibility("hidden"))) extern const struct __cex_namespace__DST DST;

