// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// NOTE: include in test as
//#include "tests/fake/include/cex/sbuf.h"


// clang-format off
#include <cex/test/fff.h>
#include <cex/cex.h>
#include "include/cex/sbuf.h"


FAKE_VALUE_FUNC(Exc, sbuf_create, sbuf_c*, u32, IAllocator)
FAKE_VALUE_FUNC(Exc, sbuf_create_static, sbuf_c*, char*, usize)
FAKE_VALUE_FUNC(Exc, sbuf_grow, sbuf_c*, u32)
FAKE_VOID_FUNC(sbuf_update_len, sbuf_c*)
FAKE_VALUE_FUNC(Exc, sbuf_replace, sbuf_c*, const str_c, const str_c)
FAKE_VALUE_FUNC(Exc, sbuf_append, sbuf_c*, str_c)
FAKE_VOID_FUNC(sbuf_clear, sbuf_c*)
FAKE_VALUE_FUNC(u32, sbuf_len, const sbuf_c*)
FAKE_VALUE_FUNC(u32, sbuf_capacity, const sbuf_c*)
FAKE_VALUE_FUNC(sbuf_c, sbuf_destroy, sbuf_c*)
FAKE_VALUE_FUNC(Exc, sbuf_vsprintf, sbuf_c*, const char*, va_list)
FAKE_VALUE_FUNC_VARARG(Exc, sbuf_sprintf, sbuf_c*, const char*, ...)
FAKE_VALUE_FUNC(str_c, sbuf_to_str, sbuf_c*)
FAKE_VALUE_FUNC(bool, sbuf_isvalid, sbuf_c*)
FAKE_VALUE_FUNC(str_c*, sbuf_iter_split, sbuf_c*, const char*, cex_iterator_s*)

const struct __module__sbuf sbuf = {
    // Autogenerated by CEX
    // clang-format off
    .create = sbuf_create,
    .create_static = sbuf_create_static,
    .grow = sbuf_grow,
    .update_len = sbuf_update_len,
    .replace = sbuf_replace,
    .append = sbuf_append,
    .clear = sbuf_clear,
    .len = sbuf_len,
    .capacity = sbuf_capacity,
    .destroy = sbuf_destroy,
    .vsprintf = sbuf_vsprintf,
    .sprintf = sbuf_sprintf,
    .to_str = sbuf_to_str,
    .isvalid = sbuf_isvalid,
    .iter_split = sbuf_iter_split,
    // clang-format on
};

// clang-format off


static void fake__sbuf__resetall(void) {
    RESET_FAKE(sbuf_create)
    RESET_FAKE(sbuf_create_static)
    RESET_FAKE(sbuf_grow)
    RESET_FAKE(sbuf_update_len)
    RESET_FAKE(sbuf_replace)
    RESET_FAKE(sbuf_append)
    RESET_FAKE(sbuf_clear)
    RESET_FAKE(sbuf_len)
    RESET_FAKE(sbuf_capacity)
    RESET_FAKE(sbuf_destroy)
    RESET_FAKE(sbuf_vsprintf)
    RESET_FAKE(sbuf_sprintf)
    RESET_FAKE(sbuf_to_str)
    RESET_FAKE(sbuf_isvalid)
    RESET_FAKE(sbuf_iter_split)
}

