// Autogenerated <fff.h> mocks
// NOTE: Do not edit, all changes can be lost

// NOTE: include in test as
//#include "tests/fake/include/cex/str.h"


// clang-format off
#include <cex/test/fff.h>
#include <cex/cex.h>
#include "include/cex/str.h"


FAKE_VALUE_FUNC(str_c, str_cstr, const char*)
FAKE_VALUE_FUNC(str_c, str_cbuf, char*, usize)
FAKE_VALUE_FUNC(str_c, str_sub, str_c, isize, isize)
FAKE_VALUE_FUNC(Exc, str_copy, str_c, char*, usize)
FAKE_VALUE_FUNC(str_c, str_vsprintf, char*, usize, const char*, va_list)
FAKE_VALUE_FUNC_VARARG(str_c, str_sprintf, char*, usize, const char*, ...)
FAKE_VALUE_FUNC(usize, str_len, str_c)
FAKE_VALUE_FUNC(bool, str_is_valid, str_c)
FAKE_VALUE_FUNC(char*, str_iter, str_c, cex_iterator_s*)
FAKE_VALUE_FUNC(isize, str_find, str_c, str_c, usize, usize)
FAKE_VALUE_FUNC(isize, str_rfind, str_c, str_c, usize, usize)
FAKE_VALUE_FUNC(bool, str_contains, str_c, str_c)
FAKE_VALUE_FUNC(bool, str_starts_with, str_c, str_c)
FAKE_VALUE_FUNC(bool, str_ends_with, str_c, str_c)
FAKE_VALUE_FUNC(str_c, str_remove_prefix, str_c, str_c)
FAKE_VALUE_FUNC(str_c, str_remove_suffix, str_c, str_c)
FAKE_VALUE_FUNC(str_c, str_lstrip, str_c)
FAKE_VALUE_FUNC(str_c, str_rstrip, str_c)
FAKE_VALUE_FUNC(str_c, str_strip, str_c)
FAKE_VALUE_FUNC(int, str_cmp, str_c, str_c)
FAKE_VALUE_FUNC(int, str_cmpi, str_c, str_c)
FAKE_VALUE_FUNC(str_c*, str_iter_split, str_c, const char*, cex_iterator_s*)
FAKE_VALUE_FUNC(Exc, str_to_f32, str_c, f32*)
FAKE_VALUE_FUNC(Exc, str_to_f64, str_c, f64*)
FAKE_VALUE_FUNC(Exc, str_to_i8, str_c, i8*)
FAKE_VALUE_FUNC(Exc, str_to_i16, str_c, i16*)
FAKE_VALUE_FUNC(Exc, str_to_i32, str_c, i32*)
FAKE_VALUE_FUNC(Exc, str_to_i64, str_c, i64*)
FAKE_VALUE_FUNC(Exc, str_to_u8, str_c, u8*)
FAKE_VALUE_FUNC(Exc, str_to_u16, str_c, u16*)
FAKE_VALUE_FUNC(Exc, str_to_u32, str_c, u32*)
FAKE_VALUE_FUNC(Exc, str_to_u64, str_c, u64*)
FAKE_VALUE_FUNC_VARARG(str_c, str_fmt, IAllocator, const char*, ...)
FAKE_VALUE_FUNC_VARARG(char*, str_cfmt, IAllocator, const char*, ...)
FAKE_VALUE_FUNC_VARARG(char*, str_tfmt, const char*, ...)
FAKE_VALUE_FUNC(char*, str_tnew, str_c)
FAKE_VALUE_FUNC(char*, str_tcopy, char*)
FAKE_VALUE_FUNC(arr$(char*), str_tsplit, char*, const char*)
FAKE_VALUE_FUNC(char*, str_tjoin, arr$(char*), const char*)

const struct __module__str str = {
    // Autogenerated by CEX
    // clang-format off
    .cstr = str_cstr,
    .cbuf = str_cbuf,
    .sub = str_sub,
    .copy = str_copy,
    .vsprintf = str_vsprintf,
    .sprintf = str_sprintf,
    .len = str_len,
    .is_valid = str_is_valid,
    .iter = str_iter,
    .find = str_find,
    .rfind = str_rfind,
    .contains = str_contains,
    .starts_with = str_starts_with,
    .ends_with = str_ends_with,
    .remove_prefix = str_remove_prefix,
    .remove_suffix = str_remove_suffix,
    .lstrip = str_lstrip,
    .rstrip = str_rstrip,
    .strip = str_strip,
    .cmp = str_cmp,
    .cmpi = str_cmpi,
    .iter_split = str_iter_split,
    .to_f32 = str_to_f32,
    .to_f64 = str_to_f64,
    .to_i8 = str_to_i8,
    .to_i16 = str_to_i16,
    .to_i32 = str_to_i32,
    .to_i64 = str_to_i64,
    .to_u8 = str_to_u8,
    .to_u16 = str_to_u16,
    .to_u32 = str_to_u32,
    .to_u64 = str_to_u64,
    .fmt = str_fmt,
    .cfmt = str_cfmt,
    .tfmt = str_tfmt,
    .tnew = str_tnew,
    .tcopy = str_tcopy,
    .tsplit = str_tsplit,
    .tjoin = str_tjoin,
    // clang-format on
};

// clang-format off


static void fake__str__resetall(void) {
    RESET_FAKE(str_cstr)
    RESET_FAKE(str_cbuf)
    RESET_FAKE(str_sub)
    RESET_FAKE(str_copy)
    RESET_FAKE(str_vsprintf)
    RESET_FAKE(str_sprintf)
    RESET_FAKE(str_len)
    RESET_FAKE(str_is_valid)
    RESET_FAKE(str_iter)
    RESET_FAKE(str_find)
    RESET_FAKE(str_rfind)
    RESET_FAKE(str_contains)
    RESET_FAKE(str_starts_with)
    RESET_FAKE(str_ends_with)
    RESET_FAKE(str_remove_prefix)
    RESET_FAKE(str_remove_suffix)
    RESET_FAKE(str_lstrip)
    RESET_FAKE(str_rstrip)
    RESET_FAKE(str_strip)
    RESET_FAKE(str_cmp)
    RESET_FAKE(str_cmpi)
    RESET_FAKE(str_iter_split)
    RESET_FAKE(str_to_f32)
    RESET_FAKE(str_to_f64)
    RESET_FAKE(str_to_i8)
    RESET_FAKE(str_to_i16)
    RESET_FAKE(str_to_i32)
    RESET_FAKE(str_to_i64)
    RESET_FAKE(str_to_u8)
    RESET_FAKE(str_to_u16)
    RESET_FAKE(str_to_u32)
    RESET_FAKE(str_to_u64)
    RESET_FAKE(str_fmt)
    RESET_FAKE(str_cfmt)
    RESET_FAKE(str_tfmt)
    RESET_FAKE(str_tnew)
    RESET_FAKE(str_tcopy)
    RESET_FAKE(str_tsplit)
    RESET_FAKE(str_tjoin)
}

