#pragma once
#include <cex/cex_base.h>
#include <stddef.h>

typedef struct
{
    alignas(64) const Allocator_i base;
    void* mem;
    void* next;
    void* max;
    // below goes sanity check stuff for debug builds
    u64 magic;
    struct
    {
        unsigned int n_allocs;
        unsigned int n_reallocs;
        unsigned int n_free;
        unsigned int n_fopen;
        unsigned int n_fclose;
        unsigned int n_open;
        unsigned int n_close;
    } stats;

} allocator_staticarena_s;

_Static_assert(alignof(allocator_staticarena_s) == 64, "align");
_Static_assert(offsetof(allocator_staticarena_s, base) == 0, "base must be the 1st struct member");
struct __cex_namespace__AllocatorStaticArena {
    // Autogenerated by CEX
    // clang-format off

    /// Static arena allocator (can be heap or stack arena)
    IAllocator      (*create)(char* buffer, usize capacity);
    IAllocator      (*destroy)(void);

    // clang-format on
};
__attribute__((visibility("hidden"))) extern const struct __cex_namespace__AllocatorStaticArena AllocatorStaticArena;

