#include "MyClass.h"

Exception
MyClass_create(MyClass_c** self, u32 x, u32 y, const Allocator_i* allc)
{
    uassert(self != NULL);

    e$except_null(*self = allc->calloc(1, sizeof(*self)))
    {
        return Error.memory;
    }

    (*self)->x = x;
    (*self)->y = y;

    return EOK;
}

void
MyClass_destroy(MyClass_c** self, const Allocator_i* allc)
{
    uassert(self != NULL);

    if (*self != NULL) {
        allc->free(*self);
        *self = NULL;
    }
}

Exception
MyClass_add(MyClass_c* self, MyClass_c* other)
{
    uassert(self != NULL);
    uassert(other != NULL);

    if (other->y == 0) {
        // NOTE: any non EOK (NULL) string treated as error
        return "y is zero";
    }

    // One-liner error check
    e$assert(other->x > 0);


    self->x += other->x;
    self->y += other->y;

    return EOK;
}

const struct __class__MyClass MyClass = {
    // Autogenerated by CEX
    // clang-format off
    .create = MyClass_create,
    .destroy = MyClass_destroy,
    .add = MyClass_add,
    // clang-format on
};
