#pragma once
#include <cex.h>

typedef struct MyClass_c
{
    u32 x;
    u32 y;
} MyClass_c;

struct __class__MyClass
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*create)(MyClass_c** self, u32 x, u32 y, const Allocator_i* allc);

void
(*destroy)(MyClass_c** self, const Allocator_i* allc);

Exception
(*add)(MyClass_c* self, MyClass_c* other);

    // clang-format on
};
extern const struct __class__MyClass MyClass; // CEX Autogen
