#pragma once
#include <cex/cex.h>

struct __module__mylib
{
    // Autogenerated by CEX
    // clang-format off

u32
(*add)(u32 a, u32 b);

u32
(*mul)(u32 a, u32 b);

    // clang-format on
};
extern const struct __module__mylib mylib; // CEX Autogen
