#include "mylib.h"

u32
mylib_add(u32 a, u32 b)
{
    return a + b;
}

u32
mylib_mul(u32 a, u32 b)
{
    // NOTE: adding a flaw to multiplication
    return a * b + 1;
}

const struct __module__mylib mylib = {
    // Autogenerated by CEX
    // clang-format off
    .add = mylib_add,
    .mul = mylib_mul,
    // clang-format on
};
