#pragma once
#include "all.h"

#if defined(CEXBUILD)

#ifndef cexy$cc
#if defined(__clang__)
#define cexy$cc "clang"
#elif defined(__GNUC__)
#define cexy$cc "gcc"
#else
# #error "Compiler type is not supported"
#endif
#endif // #ifndef cexy$cc

#ifndef cexy$cc_include
#define cexy$cc_include "-I."
#endif

#ifndef cexy$build_dir
#define cexy$build_dir "build/"
#endif

#ifndef cexy$cc_args
#define cexy$cc_args "-Wall", "-Wextra"
#endif

#ifndef cexy$ld_args
#define cexy$ld_args ""
#endif

#ifndef cexy$ld_libs
#define cexy$ld_libs ""
#endif

#ifndef cexy$cc_args_test
#define cexy$cc_args_test                                                                          \
    "-DCEXTEST", "-Wall", "-Wextra", "-Werror", "-Wno-unused-function", "-g3", "-Itests/",         \
        "-fsanitize-address-use-after-scope", "-fsanitize=address", "-fsanitize=undefined",        \
        "-fsanitize=leak", "-fstack-protector-strong"

#endif

#define cexy$description "Cex build system"
/* clang-format off */
#define cexy$epilog                                                                                \
    "\nList of #define cexy$* variables used in build system (you may redefine them)\n"            \
    "* cexy$build_dir        " cexy$build_dir "\n"                                                 \
    "* cexy$cc               " cexy$cc "\n"                                                        \
    "* cexy$cc_include       " cex$stringize(cexy$cc_include) "\n"                                 \
    "* cexy$cc_args          " cex$stringize(cexy$cc_args) "\n"                                    \
    "* cexy$cc_args_test     " cex$stringize(cexy$cc_args_test) "\n"\
    "* cexy$ld_args          " cex$stringize(cexy$ld_args) "\n"                                    \
    "* cexy$ld_libs          " cex$stringize(cexy$ld_libs) "\n"

/* clang-format on */
#define cexy$initialize() cexy.build_self(argc, argv, __FILE__)

struct __module__cexy
{
    // Autogenerated by CEX
    // clang-format off

void            (*build_self)(int argc, char** argv, const char* cex_source);
bool            (*src_changed)(const char* target_path, arr$(char*) src_array);
bool            (*src_include_changed)(const char* target_path, const char* src_path, arr$(char*) alt_include_path);
char*           (*target_make)(const char* src_path, const char* build_dir, const char* name_or_extension, IAllocator allocator);
Exception       (*test_create)(const char* test_path);
    // clang-format on
};
__attribute__ ((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
#endif // #if defined(CEXBUILD)
