#pragma once
#include "all.h"

/// Makes string literal with ansi colored test
#define io$ansi(text, ansi_col) "\033[" ansi_col "m" text "\033[0m"

/**
Cross-platform IO namespace

- Read all file content (low level api)
```c

test$case(test_readall)
{
    // Open new file
    FILE* file;
    e$ret(io.fopen(&file, "tests/data/text_file_50b.txt", "r"));


    // get file size 
    tassert_eq(50, io.file.size(file));

    // Read all content
    str_s content;
    e$ret(io.fread_all(file, &content, mem$));
    mem$free(mem$, content.buf); // content.buf is allocated by mem$ !

    // Cleanup
    io.fclose(&file); // file will be set to NULL
    tassert(file == NULL);

    return EOK;
}

```

- File load/save (easy api)
```c

test$case(test_fload_save)
{
    tassert_eq(Error.ok, io.file.save("tests/data/text_file_write.txt", "Hello from CEX!\n"));
    char* content = io.file.load("tests/data/text_file_write.txt", mem$);
    tassert(content);
    tassert_eq(content, "Hello from CEX!\n");
    mem$free(mem$, content);
    return EOK;
}

```

- File read/write lines 

```c
test$case(test_write_line)
{
    FILE* file;
    tassert_eq(Error.ok, io.fopen(&file, "tests/data/text_file_write.txt", "w+"));

    str_s content;
    mem$scope(tmem$, _)
    {
        // Writing line by line
        tassert_eq(EOK, io.file.writeln(file, "hello"));
        tassert_eq(EOK, io.file.writeln(file, "world"));

        // Reading line by line
        io.rewind(file);

        // easy api - backed by temp allocator
        tassert_eq("hello", io.file.readln(file, _));

        // low-level api (using heap allocator, needs free!)
        tassert_er(EOK, io.fread_line(file, &content, mem$));
        tassert(str.slice.eq(content, str$s("world")));
        mem$free(mem$, content.buf);
    }

    io.fclose(&file);
    return EOK;
}
```

*/

struct __cex_namespace__io {
    // Autogenerated by CEX
    // clang-format off

    void            (*fclose)(FILE** file);
    Exception       (*fflush)(FILE* file);
    int             (*fileno)(FILE* file);
    Exception       (*fopen)(FILE** file, char* filename, char* mode);
    Exc             (*fprintf)(FILE* stream, char* format,...);
    Exception       (*fread)(FILE* file, void* obj_buffer, usize obj_el_size, usize* obj_count);
    Exception       (*fread_all)(FILE* file, str_s* s, IAllocator allc);
    Exception       (*fread_line)(FILE* file, str_s* s, IAllocator allc);
    Exception       (*fseek)(FILE* file, long offset, int whence);
    Exception       (*ftell)(FILE* file, usize* size);
    Exception       (*fwrite)(FILE* file, void* obj_buffer, usize obj_el_size, usize obj_count);
    bool            (*isatty)(FILE* file);
    int             (*printf)(char* format,...);
    void            (*rewind)(FILE* file);

    struct {
        char*           (*load)(char* path, IAllocator allc);
        char*           (*readln)(FILE* file, IAllocator allc);
        Exception       (*save)(char* path, char* contents);
        usize           (*size)(FILE* file);
        Exception       (*writeln)(FILE* file, char* line);
    } file;

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__io io;

