#pragma once
#include "all.h"

#define io$ansi(text, ansi_col) "\033[" ansi_col "m" text "\033[0m"

struct __cex_namespace__io {
    // Autogenerated by CEX
    // clang-format off

    void            (*fclose)(FILE** file);
    Exception       (*fflush)(FILE* file);
    int             (*fileno)(FILE* file);
    Exception       (*fopen)(FILE** file, const char* filename, const char* mode);
    Exc             (*fprintf)(FILE* stream, const char* format,...);
    Exception       (*fread)(FILE* file, void* obj_buffer, usize obj_el_size, usize* obj_count);
    Exception       (*fread_all)(FILE* file, str_s* s, IAllocator allc);
    Exception       (*fread_line)(FILE* file, str_s* s, IAllocator allc);
    Exception       (*fseek)(FILE* file, long offset, int whence);
    Exception       (*ftell)(FILE* file, usize* size);
    Exception       (*fwrite)(FILE* file, const void* obj_buffer, usize obj_el_size, usize obj_count);
    bool            (*isatty)(FILE* file);
    int             (*printf)(const char* format,...);
    void            (*rewind)(FILE* file);

    struct {
        char*           (*load)(const char* path, IAllocator allc);
        char*           (*readln)(FILE* file, IAllocator allc);
        Exception       (*save)(const char* path, const char* contents);
        usize           (*size)(FILE* file);
        Exception       (*writeln)(FILE* file, char* line);
    } file;

    // clang-format on
};
__attribute__((visibility("hidden"))) extern const struct __cex_namespace__io io;

