#pragma once
#include "all.h"

typedef char* sbuf_c;

typedef struct
{
    struct
    {
        u32 magic : 16;   // used for sanity checks
        u32 elsize : 8;   // maybe multibyte strings in the future?
        u32 nullterm : 8; // always zero to prevent usage of direct buffer
    } header;
    u32 length;
    u32 capacity;
    const Allocator_i* allocator;
} __attribute__((packed)) sbuf_head_s;

_Static_assert(alignof(sbuf_head_s) == 1, "align");
_Static_assert(alignof(sbuf_head_s) == alignof(char), "align");

struct __module__sbuf
{
    // Autogenerated by CEX
    // clang-format off

Exception       (*append)(sbuf_c* self, const char* s);
Exception       (*appendf)(sbuf_c* self, const char* format, ...);
Exception       (*appendfva)(sbuf_c* self, const char* format, va_list va);
u32             (*capacity)(const sbuf_c* self);
void            (*clear)(sbuf_c* self);
sbuf_c          (*create)(u32 capacity, IAllocator allocator);
sbuf_c          (*create_static)(char* buf, usize buf_size);
sbuf_c          (*create_temp)(void);
sbuf_c          (*destroy)(sbuf_c* self);
Exception       (*grow)(sbuf_c* self, u32 new_capacity);
bool            (*isvalid)(sbuf_c* self);
u32             (*len)(const sbuf_c* self);
void            (*shrink)(sbuf_c* self, u32 new_length);
void            (*update_len)(sbuf_c* self);
    // clang-format on
};
__attribute__ ((visibility("hidden"))) extern const struct __module__sbuf sbuf; // CEX Autogen
