#pragma once
#include <cex/cex.h>

typedef struct App_c {
    bool is_flag;
    i64 num_arg;
    char* name_arg;
    char** args;
    u32 args_count;
    IAllocator allocator;
} App_c;

struct __cex_namespace__App {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(App_c* app, i32 argc, char* argv[], IAllocator allocator);
    void            (*destroy)(App_c* app, IAllocator allocator);
    Exception       (*main)(App_c* app, IAllocator allocator);

    // clang-format on
};
__attribute__((visibility("hidden"))) extern const struct __cex_namespace__App App;

