#pragma once
#include <cex/cex.h>

typedef struct App_c {
    bool is_flag;
    i64 num_arg;
    char* name_arg;
    char** args;
    u32 args_count;
    IAllocator allocator;
} App_c;

struct __class__App
{
    // Autogenerated by CEX
    // clang-format off

Exception
(*create)(App_c* app, i32 argc, char* argv[], IAllocator allocator);

Exception
(*main)(App_c* app, IAllocator allocator);

void
(*destroy)(App_c* app, IAllocator allocator);

    // clang-format on
};
extern const struct __class__App App; // CEX Autogen
