#pragma once
#include <cex/cex.h>

struct __cex_namespace__mylib {
    // Autogenerated by CEX
    // clang-format off

    u32             (*add)(u32 a, u32 b);
    u32             (*mul)(u32 a, u32 b);

    // clang-format on
};
__attribute__((visibility("hidden"))) extern const struct __cex_namespace__mylib mylib;

