#pragma once
#include "all.h"

#if defined(CEXBUILD)

#ifndef cexy$cc
#if defined(__clang__)
#define cexy$cc "clang"
#elif defined(__GNUC__)
#define cexy$cc "gcc"
#else
# #error "Compiler type is not supported"
#endif
#endif // #ifndef cexy$cc

#ifndef cexy$cc_include
#define cexy$cc_include "-I."
#endif

#define cexy$run

#define cexy$initialize() cexy.build_self(argc, argv, __FILE__)

__attribute__((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
__attribute__((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
__attribute__ ((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
__attribute__ ((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
struct __module__cexy
{
    // Autogenerated by CEX
    // clang-format off

void            (*build_self)(int argc, char** argv, const char* cex_source);
bool            (*src_changed)(const char* target_path, const arr$(char*) src_array);
bool            (*src_include_changed)(const char* target_path, const char* src_path, arr$(char*) alt_include_path);
    // clang-format on
};
__attribute__ ((visibility("hidden"))) extern const struct __module__cexy cexy; // CEX Autogen
#endif // #if defined(CEXBUILD)
