#pragma once
#include "all.h"
#include <stdio.h>


typedef struct io_c
{
    FILE* file;
    usize _fsize;
    char* _fbuf;
    usize _fbuf_size;
    IAllocator _allocator;
    struct
    {
        u32 is_attached : 1;

    } _flags;
} io_c;


struct __module__io
{
    // Autogenerated by CEX
    // clang-format off

void            (*close)(io_c* self);
io_c            (*fattach)(FILE* fh, IAllocator allocator);
int             (*fileno)(io_c* self);
char*           (*fload)(const char* path, IAllocator allc);
Exception       (*flush)(io_c* self);
Exception       (*fprintf)(FILE* stream, const char* format, ...);
bool            (*isatty)(io_c* self);
Exception       (*open)(io_c* self, const char* filename, const char* mode, IAllocator allocator);
void            (*printf)(const char* format, ...);
Exception       (*read)(io_c* self, void* obj_buffer, usize obj_el_size, usize* obj_count);
Exception       (*readall)(io_c* self, str_s* s);
Exception       (*readline)(io_c* self, str_s* s);
void            (*rewind)(io_c* self);
Exception       (*seek)(io_c* self, long offset, int whence);
usize           (*size)(io_c* self);
Exception       (*tell)(io_c* self, usize* size);
Exception       (*write)(io_c* self, void* obj_buffer, usize obj_el_size, usize obj_count);
    // clang-format on
};
extern const struct __module__io io; // CEX Autogen
