#pragma once
#include "all.h"

struct __module__io
{
    // Autogenerated by CEX
    // clang-format off

void            (*fclose)(FILE** file);
Exception       (*fflush)(FILE* file);
int             (*fileno)(FILE* file);
Exception       (*fopen)(FILE** file, const char* filename, const char* mode);
Exception       (*fprintf)(FILE* stream, const char* format, ...);
Exception       (*fread)(FILE* file, void* obj_buffer, usize obj_el_size, usize* obj_count);
Exception       (*fread_all)(FILE* file, str_s* s, IAllocator allc);
Exception       (*fread_line)(FILE* file, str_s* s, IAllocator allc);
Exception       (*fseek)(FILE* file, long offset, int whence);
Exception       (*ftell)(FILE* file, usize* size);
Exception       (*fwrite)(FILE* file, const void* obj_buffer, usize obj_el_size, usize obj_count);
bool            (*isatty)(FILE* file);
void            (*printf)(const char* format, ...);
void            (*rewind)(FILE* file);

struct {  // sub-module .file >>>
    char*           (*load)(const char* path, IAllocator allc);
    char*           (*readln)(FILE* file, IAllocator allc);
    Exception       (*save)(const char* path, const char* contents);
    usize           (*size)(FILE* file);
    Exception       (*writeln)(FILE* file, char* line);
} file;  // sub-module .file <<<
    // clang-format on
};
__attribute__ ((visibility("hidden"))) extern const struct __module__io io; // CEX Autogen
