#pragma once
#include "all.h"
#include <stdio.h>

struct __module__io
{
    // Autogenerated by CEX
    // clang-format off

void            (*fclose)(FILE** file);
Exception       (*fflush)(FILE* file);
int             (*fileno)(FILE* file);
char*           (*fload)(const char* path, IAllocator allc);
Exception       (*fopen)(FILE** file, const char* filename, const char* mode);
Exception       (*fprintf)(FILE* stream, const char* format, ...);
Exception       (*fread)(FILE* file, void* obj_buffer, usize obj_el_size, usize* obj_count);
char*           (*fread_line)(FILE* file, IAllocator allc);
Exception       (*fsave)(const char* path, const char* contents);
Exception       (*fseek)(FILE* file, long offset, int whence);
usize           (*fsize)(FILE* file);
Exception       (*ftell)(FILE* file, usize* size);
Exception       (*fwrite)(FILE* file, const void* obj_buffer, usize obj_el_size, usize obj_count);
Exception       (*fwrite_line)(FILE* file, char* line);
bool            (*isatty)(FILE* file);
void            (*printf)(const char* format, ...);
Exception       (*read_all)(FILE* file, str_s* s, IAllocator allc);
Exception       (*read_line)(FILE* file, str_s* s, IAllocator allc);
void            (*rewind)(FILE* file);
    // clang-format on
};
extern const struct __module__io io; // CEX Autogen
