#pragma once
#include "all.h"

typedef char* sbuf_c;

typedef struct
{
    struct
    {
        u32 magic : 16;   // used for sanity checks
        u32 elsize : 8;   // maybe multibyte strings in the future?
        u32 nullterm : 8; // always zero to prevent usage of direct buffer
    } header;
    u32 length;
    u32 capacity;
    const Allocator2_i* allocator;
} __attribute__((packed)) sbuf_head_s;

_Static_assert(alignof(sbuf_head_s) == 1, "align");
_Static_assert(alignof(sbuf_head_s) == alignof(char), "align");


struct __module__sbuf
{
    // Autogenerated by CEX
    // clang-format off

sbuf_c
(*create)(u32 capacity, IAllocator allocator);

sbuf_c
(*create_temp)(void);

sbuf_c
(*create_static)(char* buf, usize buf_size);

Exception
(*grow)(sbuf_c* self, u32 new_capacity);

void
(*update_len)(sbuf_c* self);

Exception
(*replace)(sbuf_c* self, const char* oldstr, const char* newstr);

void
(*clear)(sbuf_c* self);

u32
(*len)(const sbuf_c* self);

u32
(*capacity)(const sbuf_c* self);

sbuf_c
(*destroy)(sbuf_c* self);

Exception
(*appendf)(sbuf_c* self, const char* format, ...);

Exception
(*append)(sbuf_c* self, const char* s);

bool
(*isvalid)(sbuf_c* self);

    // clang-format on
};
extern const struct __module__sbuf sbuf; // CEX Autogen
