/**
 * @file
 * @brief
 */

#pragma once
#include "all.h"
#include <stdalign.h>
#include <stdint.h>



struct __module__str
{
    // Autogenerated by CEX
    // clang-format off

str_s
(*cstr)(const char* ccharptr);

str_s
(*cbuf)(char* s, usize length);

bool
(*eq)(const char* a, const char* b);

str_s
(*sub)(str_s s, isize start, isize end);

Exception
(*copy)(str_s s, char* dest, usize destlen);

str_s
(*vsprintf)(char* dest, usize dest_len, const char* format, va_list va);

str_s
(*sprintf)(char* dest, usize dest_len, const char* format, ...);

usize
(*len)(str_s s);

bool
(*is_valid)(str_s s);

char*
(*iter)(str_s s, cex_iterator_s* iterator);

isize
(*find)(str_s s, str_s needle, usize start, usize end);

isize
(*rfind)(str_s s, str_s needle, usize start, usize end);

bool
(*contains)(str_s s, str_s needle);

bool
(*starts_with)(str_s s, str_s needle);

bool
(*ends_with)(str_s s, str_s needle);

str_s
(*remove_prefix)(str_s s, str_s prefix);

str_s
(*remove_suffix)(str_s s, str_s suffix);

str_s
(*lstrip)(str_s s);

str_s
(*rstrip)(str_s s);

str_s
(*strip)(str_s s);

int
(*cmp)(str_s self, str_s other);

int
(*cmpi)(str_s self, str_s other);

str_s*
(*iter_split)(str_s s, const char* split_by, cex_iterator_s* iterator);

Exception
(*to_f32)(str_s self, f32* num);

Exception
(*to_f64)(str_s self, f64* num);

Exception
(*to_i8)(str_s self, i8* num);

Exception
(*to_i16)(str_s self, i16* num);

Exception
(*to_i32)(str_s self, i32* num);

Exception
(*to_i64)(str_s self, i64* num);

Exception
(*to_u8)(str_s self, u8* num);

Exception
(*to_u16)(str_s self, u16* num);

Exception
(*to_u32)(str_s self, u32* num);

Exception
(*to_u64)(str_s self, u64* num);

str_s
(*fmt)(IAllocator allc, const char* format, ...);

char*
(*cfmt)(IAllocator allc, const char* format, ...);

char*
(*tfmt)(const char* format, ...);

char*
(*tnew)(str_s s);

char*
(*tcopy)(char* s);

arr$(char*)
(*tsplit)(char* s, const char* split_by);

char*
(*tjoin)(arr$(char*) str_arr, const char* join_by);

    // clang-format on
};
extern const struct __module__str str; // CEX Autogen
