/**
 * @file
 * @brief
 */

#pragma once
#include "all.h"
#include <stdalign.h>
#include <stdint.h>



struct __module__str
{
    // Autogenerated by CEX
    // clang-format off

char*           (*clone)(char* s, IAllocator allc);
Exception       (*copy)(char* dest, const char* src, usize destlen);
bool            (*ends_with)(const char* str, const char* suffix);
bool            (*eq)(const char* a, const char* b);
char*           (*find)(const char* haystack, const char* needle);
char*           (*findr)(const char* haystack, const char* needle);
char*           (*fmt)(IAllocator allc, const char* format, ...);
char*           (*join)(arr$(char*) str_arr, const char* join_by, IAllocator allc);
usize           (*len)(char* s);
char*           (*replace)(const char* str, const char* old_sub, const char* new_sub, IAllocator allc);
str_s           (*sbuf)(char* s, usize length);
arr$(char*)     (*split)(char* s, const char* split_by, IAllocator allc);
Exception       (*sprintf)(char* dest, usize dest_len, const char* format, ...);
str_s           (*sstr)(const char* ccharptr);
bool            (*starts_with)(const char* str, const char* prefix);
str_s           (*sub)(const char* s, isize start, isize end);
Exception       (*vsprintf)(char* dest, usize dest_len, const char* format, va_list va);

struct {  // sub-module .slice >>>
    char*           (*clone)(str_s s, IAllocator allc);
    int             (*cmp)(str_s self, str_s other);
    int             (*cmpi)(str_s self, str_s other);
    Exception       (*copy)(char* dest, str_s src, usize destlen);
    bool            (*ends_with)(str_s s, str_s suffix);
    bool            (*eq)(str_s a, str_s b);
    str_s*          (*iter_split)(str_s s, const char* split_by, cex_iterator_s* iterator);
    str_s           (*lstrip)(str_s s);
    str_s           (*remove_prefix)(str_s s, str_s prefix);
    str_s           (*remove_suffix)(str_s s, str_s suffix);
    str_s           (*rstrip)(str_s s);
    bool            (*starts_with)(str_s str, str_s prefix);
    str_s           (*strip)(str_s s);
    str_s           (*sub)(str_s s, isize start, isize end);
} slice;  // sub-module .slice <<<

struct {  // sub-module .convert >>>
    Exception       (*to_f32)(const char* s, f32* num);
    Exception       (*to_f64)(const char* s, f64* num);
    Exception       (*to_i16)(str_s self, i16* num);
    Exception       (*to_i32)(str_s self, i32* num);
    Exception       (*to_i64)(str_s self, i64* num);
    Exception       (*to_i8)(str_s self, i8* num);
    Exception       (*to_u16)(str_s self, u16* num);
    Exception       (*to_u32)(str_s self, u32* num);
    Exception       (*to_u64)(str_s self, u64* num);
    Exception       (*to_u8)(str_s self, u8* num);
} convert;  // sub-module .convert <<<
    // clang-format on
};
extern const struct __module__str str; // CEX Autogen
