#pragma once
#include <cex/cex.h>
#include <stddef.h>

typedef struct
{
    alignas(64) const Allocator_i base;
    void* mem;
    void* next;
    void* max;
    // below goes sanity check stuff for debug builds
    u64 magic;
    struct
    {
        unsigned int n_allocs;
        unsigned int n_reallocs;
        unsigned int n_free;
        unsigned int n_fopen;
        unsigned int n_fclose;
        unsigned int n_open;
        unsigned int n_close;
    } stats;

} allocator_staticarena_s;

_Static_assert(alignof(allocator_staticarena_s) == 64, "align");
_Static_assert(offsetof(allocator_staticarena_s, base) == 0, "base must be the 1st struct member");
struct __class__AllocatorStaticArena
{
    // Autogenerated by CEX
    // clang-format off

/**
 * @brief Static arena allocator (can be heap or stack arena)
 *
 * Static allocator should be created at the start of the application (maybe in main()),
 * and freed after app shutdown.
 *
 * Note: memory leaks are not caught by sanitizers, if you forget to call
 * AllocatorStaticArena.destroy() sanitizers will be silent.
 *
 * No realloc() supported by this arena!
 *
 * @param buffer - pointer to memory buffer
 * @param capacity - capacity of a buffer (minimal requires is 1024)
 * @return  allocator instance
 */
const Allocator_i*
(*create)(char* buffer, usize capacity);

const Allocator_i*
(*destroy)(void);

    // clang-format on
};
extern const struct __class__AllocatorStaticArena AllocatorStaticArena; // CEX Autogen
